{
	"version": 1656449195,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/playablecharacter-sheet0.png",
		"images/playablecharacter-sheet1.png",
		"images/playablecharacter-sheet2.png",
		"images/tilemap.png",
		"images/solidcollide.png",
		"images/bush-sheet0.png",
		"images/bush-sheet1.png",
		"images/leaf.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/coinparticle.png",
		"images/coincounter.png",
		"images/dialoguebox.png",
		"images/dialoguepic-sheet0.png",
		"images/dialoguepic-sheet1.png",
		"images/speakername.png",
		"images/dialoguetext.png",
		"images/interactivenpc-sheet0.png",
		"images/interactivenpc-sheet1.png",
		"images/interactivenpc-sheet2.png",
		"images/pressspace-sheet0.png",
		"images/bluetint.png",
		"images/doorway-sheet0.png",
		"images/fadetoblack.png",
		"images/entrence-sheet0.png",
		"images/solidobject-sheet0.png",
		"images/enemy-sheet0.png",
		"images/itemstext.png",
		"images/cliff.png",
		"images/selectitem-sheet0.png",
		"images/shopkeeper-sheet0.png",
		"images/shopkeeper-sheet1.png",
		"images/shopbg-sheet0.png",
		"images/text.png",
		"images/hpbg.png",
		"images/hp.png",
		"images/twinkle-sheet0.png",
		"images/twinkle-sheet1.png",
		"images/goblin-sheet0.png",
		"images/goblin-sheet1.png",
		"images/goblin-sheet2.png",
		"images/water-sheet0.png",
		"images/water-sheet1.png",
		"images/cliffalt.png",
		"images/playerattackhitbox-sheet0.png",
		"images/roomproperties-sheet0.png",
		"images/cutscene-sheet0.png",
		"images/spr_realistic_explosion-sheet0.png",
		"images/spr_realistic_explosion-sheet1.png",
		"images/spr_realistic_explosion-sheet2.png",
		"images/home_run-sheet0.png",
		"images/home_run-sheet1.png",
		"images/home_run-sheet2.png",
		"images/home_run-sheet3.png",
		"images/home_run-sheet4.png",
		"images/home_run-sheet5.png",
		"images/puzzlesquaretimer.png",
		"images/go-sheet0.png",
		"images/puzzlesquarebg-sheet0.png",
		"images/puzzlesquarepieces.png",
		"images/healthbeam.png",
		"images/healcrystal-sheet0.png",
		"images/torch-sheet0.png",
		"images/shakybridge.png",
		"images/wizardprojectile-sheet0.png",
		"images/wizardprojectile-sheet1.png",
		"images/bosshpbg.png",
		"images/bosshp-sheet0.png",
		"images/crossedout-sheet0.png",
		"images/discord-sheet0.png",
		"images/damage.png",
		"images/mobileinv-sheet0.png",
		"images/mobileattack-sheet0.png",
		"images/mobilejoystickbg-sheet0.png",
		"images/mobilejoystick-sheet0.png",
		"media/everything is happy.m4a",
		"media/everything is happy.ogg",
		"media/nothing here.m4a",
		"media/nothing here.ogg",
		"media/awful silence.m4a",
		"media/awful silence.ogg",
		"media/coin.m4a",
		"media/coin.ogg",
		"media/bushhit.m4a",
		"media/bushhit.ogg",
		"media/death.m4a",
		"media/death.ogg",
		"media/explode.m4a",
		"media/explode.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/goblindie.m4a",
		"media/goblindie.ogg",
		"media/hurt.m4a",
		"media/hurt.ogg",
		"media/levelup.m4a",
		"media/levelup.ogg",
		"media/moveselect.m4a",
		"media/moveselect.ogg",
		"media/select.m4a",
		"media/select.ogg",
		"media/dialogue.m4a",
		"media/dialogue.ogg",
		"media/slice.m4a",
		"media/slice.ogg",
		"media/nobody here.m4a",
		"media/nobody here.ogg",
		"media/home run.m4a",
		"media/home run.ogg",
		"media/alerted.m4a",
		"media/alerted.ogg",
		"media/in the mountains.m4a",
		"media/in the mountains.ogg",
		"media/nothing there.m4a",
		"media/nothing there.ogg",
		"media/heal.m4a",
		"media/heal.ogg",
		"media/i cant spell smal gobln.m4a",
		"media/i cant spell smal gobln.ogg",
		"media/an intense battle.m4a",
		"media/an intense battle.ogg",
		"media/goblin camp.m4a",
		"media/goblin camp.ogg",
		"media/the puzzle square.m4a",
		"media/the puzzle square.ogg",
		"media/wow is that boss music.m4a",
		"media/wow is that boss music.ogg",
		"media/theend.m4a",
		"media/theend.ogg",
		"media/grow.m4a",
		"media/grow.ogg",
		"media/a huge mistake.m4a",
		"media/a huge mistake.ogg",
		"media/5 dollars.m4a",
		"media/5 dollars.ogg",
		"media/hol up.m4a",
		"media/hol up.ogg",
		"media/extra extra small t-shirt.m4a",
		"media/extra extra small t-shirt.ogg",
		"media/eaiugh.m4a",
		"media/eaiugh.ogg",
		"media/one size too small.m4a",
		"media/one size too small.ogg",
		"media/the beginning.m4a",
		"media/the beginning.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}